-- @formatter:off
-- An advisory can go in an event's TMI package, and every advisory gains an enforceable validity
-- window (VATUSA/OIS#537).
--
-- ## Why new columns, when the valid period already exists
--
-- It exists only as free text inside `structured` jsonb, and that was deliberate:
-- `models/mod.rs` explains that `DDHHMM` is kept "as written rather than parsed, because the document
-- is the contract and a round-trip through a timestamp would have to invent a month and year the
-- source never states."
--
-- That reasoning still holds, and this does not undo it. A **machine-enforced window** is a different
-- object from the **printed document line**. The columns below are set once at authoring time from the
-- same input that produces the printed period, and are never re-derived by parsing the string back
-- out. The codebase already draws this distinction for ground stops: `repos/tmu.rs` warns that
-- reimplementing the rule elsewhere "would make the generated advisory state an end the system does
-- not enforce, which is the drift #508 exists to prevent."
--
-- Both nullable. Every advisory written before this has no window and must keep expiring never,
-- rather than being cancelled on its next cleanup pass because NULL compared as "long past".

alter table tmu.advisories
    add column if not exists valid_from timestamptz,
    add column if not exists valid_to   timestamptz;

comment on column tmu.advisories.valid_from is
    'Start of the enforceable validity window. Set at authoring from the same input as the printed '
    'period; never parsed back out of the document text. NULL for advisories authored before #537.';
comment on column tmu.advisories.valid_to is
    'End of the enforceable window. The cleanup pass cancels the advisory ~30 minutes after this. '
    'NULL means no window, and such an advisory is never auto-cancelled.';

-- Drives the cleanup pass's lookup, which is the only query filtering on it.
create index if not exists idx_tmu_advisories_valid_to
    on tmu.advisories (valid_to)
    where valid_to is not null and status in ('draft', 'published');

-- Admit 'advisory' as a package item kind.
--
-- `0021_events_tmi_packages.sql` declared the check inline, so its name was generated by Postgres
-- rather than chosen. Dropping it by a guessed name would silently no-op under
-- `drop constraint if exists` and leave the old constraint in force -- the insert would then fail at
-- runtime with the new kind rejected. So the existing check on `kind` is found and dropped by lookup,
-- and the replacement is named explicitly so no future migration has to guess again.
do $$
declare
    c text;
begin
    for c in
        select con.conname
          from pg_constraint con
          join pg_attribute att
            on att.attrelid = con.conrelid
           and att.attnum = any (con.conkey)
         where con.conrelid = 'events.tmi_package_item'::regclass
           and con.contype = 'c'
           and att.attname = 'kind'
    loop
        execute format('alter table events.tmi_package_item drop constraint %I', c);
    end loop;
end $$;

alter table events.tmi_package_item
    add constraint tmi_package_item_kind_check
    check (kind in ('program', 'restriction', 'ground_stop', 'advisory'));
