//! OpenAPI document for the OIS API. Emitted at `/docs/api/v1/openapi.json`; the web
//! + desktop clients are generated from it (see docs/architecture/api-conventions.md).

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "OIS API",
        version = "0.1.0",
        description = "VATUSA Event Operational Information System API"
    ),
    paths(
        crate::handlers::health::health,
        crate::handlers::auth::me,
        crate::handlers::auth::vatsim_login,
        crate::handlers::auth::vatsim_callback,
        crate::handlers::auth::logout,
        crate::handlers::users::search_users,
        crate::handlers::facilities::list_facilities,
        crate::handlers::facilities::get_facility,
        crate::handlers::access::get_access_catalog,
        crate::handlers::access::get_self_access,
        crate::handlers::access::get_user_access,
        crate::handlers::access::update_user_access,
        crate::handlers::tmu::list_tmis,
        crate::handlers::tmu::create_tmi,
        crate::handlers::tmu::update_tmi,
        crate::handlers::tmu::publish_tmi,
        crate::handlers::tmu::cancel_tmi,
        crate::handlers::tmu::delete_tmi,
        crate::handlers::tmu::list_programs,
        crate::handlers::tmu::upsert_program,
        crate::handlers::tmu::delete_program,
        crate::handlers::tmu::list_ground_stops,
        crate::handlers::tmu::create_ground_stop,
        crate::handlers::tmu::publish_ground_stop,
        crate::handlers::tmu::cancel_ground_stop,
        crate::handlers::tmu::delete_ground_stop,
        crate::handlers::events::list_events,
        crate::handlers::events::get_event,
        crate::handlers::events::get_event_dcc,
        crate::handlers::events::update_event_dcc,
        crate::handlers::events::list_event_facilities,
        crate::handlers::events::upsert_event_facility,
        crate::handlers::events::delete_event_facility,
        crate::handlers::events::list_event_rates,
        crate::handlers::events::upsert_event_rate,
        crate::handlers::events::delete_event_rate,
        crate::handlers::events::list_event_staffing,
        crate::handlers::events::upsert_event_staffing,
        crate::handlers::events::delete_event_staffing,
        crate::handlers::events::list_event_packages,
        crate::handlers::events::create_event_package,
        crate::handlers::events::delete_event_package,
        crate::handlers::events::add_event_package_item,
        crate::handlers::events::delete_event_package_item,
        crate::handlers::events::activate_event_package,
        crate::handlers::flow::list_fcas,
        crate::handlers::flow::create_fca,
        crate::handlers::flow::update_fca,
        crate::handlers::flow::delete_fca,
        crate::handlers::flow::fca_traffic,
        crate::handlers::flow::mark_release,
        crate::handlers::flow::clear_release,
        crate::handlers::flow::reorder_fca,
        crate::handlers::flow::fca_counts,
        crate::handlers::flow::aircraft_route,
        crate::handlers::flow::list_traffic,
        crate::handlers::flow::data_status,
        crate::handlers::flow::data_refresh,
        crate::handlers::flow::route_coverage,
        crate::handlers::runway::get_runway,
        crate::handlers::runway::put_runway,
        crate::handlers::feed::feed_status,
        crate::handlers::feed::airport_flow,
        crate::handlers::feed::list_departures,
        crate::handlers::feed::taxi_stats,
        crate::handlers::feed::issue_cfr,
        crate::handlers::feed::release_cfr,
        crate::handlers::audit::list_audit_logs,
        crate::handlers::service_accounts::list_service_accounts,
        crate::handlers::service_accounts::create_service_account,
        crate::handlers::service_accounts::rotate_service_account,
        crate::handlers::service_accounts::disable_service_account,
        crate::handlers::service_accounts::set_service_account_roles,
    ),
    components(schemas(
        crate::models::MeBody,
        crate::models::UserSummary,
        crate::models::FacilityBody,
        crate::models::AccessCatalogBody,
        crate::models::SelfAccessBody,
        crate::models::UserAccessBody,
        crate::models::ScopeAccess,
        crate::models::UpdateUserAccessRequest,
        crate::models::ScopeUpdate,
        crate::models::TmiBody,
        crate::models::CreateTmiRequest,
        crate::models::UpdateTmiRequest,
        crate::models::GateRule,
        crate::models::ProgramBody,
        crate::models::UpsertProgramRequest,
        crate::models::GroundStopBody,
        crate::models::CreateGroundStopRequest,
        crate::models::EventBody,
        crate::models::DccRequestBody,
        crate::models::UpdateDccRequest,
        crate::models::FacilitySupportBody,
        crate::models::UpsertFacilitySupportRequest,
        crate::models::AirportRateBody,
        crate::models::UpsertAirportRateRequest,
        crate::models::StaffingRequestBody,
        crate::models::UpsertStaffingRequest,
        crate::models::TmiPackageBody,
        crate::models::TmiPackageItemBody,
        crate::models::CreatePackageRequest,
        crate::models::AddPackageItemRequest,
        crate::models::FcaBody,
        crate::models::UpsertFcaRequest,
        crate::models::FcaFlight,
        crate::models::ReleaseRequest,
        crate::models::ReorderRequest,
        crate::models::AircraftRoute,
        crate::models::RouteWaypoint,
        crate::models::DataStatus,
        crate::feed::coverage::CoverageReport,
        crate::feed::coverage::UnresolvedToken,
        crate::feed::runway::RunwayBoard,
        crate::feed::runway::RunwayEnd,
        crate::feed::runway::RunwayArrival,
        crate::feed::runway::RunwayDemand,
        crate::feed::runway::RunwayConfigRequest,
        crate::models::TrafficAircraft,
        crate::handlers::feed::FeedStatusBody,
        crate::feed::flow::Flow,
        crate::feed::flow::FlowFlight,
        crate::feed::taxi::TaxiField,
        crate::feed::taxi::TaxiActive,
        crate::models::DepartureFlight,
        crate::models::DeparturesResponse,
        crate::models::IssueCfrRequest,
        crate::models::IssuedCfrBody,
        crate::models::AuditLogEntry,
        crate::models::AuditLogPage,
        crate::models::CreateServiceAccountRequest,
        crate::models::SetServiceAccountRolesRequest,
        crate::models::ServiceAccountBody,
        crate::models::ServiceAccountTokenBody,
    )),
    tags(
        (name = "system", description = "Health"),
        (name = "auth", description = "Authentication + current user"),
        (name = "users", description = "User directory"),
        (name = "facilities", description = "ARTCC directory"),
        (name = "access", description = "Fine-grained access control"),
        (name = "tmu", description = "Traffic management (NTML / ADV / TMI)"),
        (name = "events", description = "VATUSA events + per-event planning"),
        (name = "flow", description = "Flow constrained areas (FCAs)"),
        (name = "feed", description = "Live VATSIM traffic feed"),
        (name = "audit", description = "Audit log"),
        (name = "service-accounts", description = "Machine client credentials")
    )
)]
pub struct ApiDoc;
