//! OpenAPI document for the OIS API. Emitted at `/docs/api/v1/openapi.json`; the web
//! + desktop clients are generated from it (see docs/architecture/api-conventions.md).

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "OIS API",
        version = "0.1.0",
        description = "VATUSA Event Operational Information System API"
    ),
    paths(
        crate::handlers::health::health,
        crate::handlers::auth::me,
        crate::handlers::auth::vatsim_login,
        crate::handlers::auth::vatsim_callback,
        crate::handlers::auth::logout,
        crate::handlers::users::search_users,
        crate::handlers::facilities::list_facilities,
        crate::handlers::facilities::get_facility,
        crate::handlers::access::get_access_catalog,
        crate::handlers::access::get_self_access,
        crate::handlers::access::get_user_access,
        crate::handlers::access::update_user_access,
        crate::handlers::tmu::list_tmis,
        crate::handlers::tmu::create_tmi,
        crate::handlers::tmu::update_tmi,
        crate::handlers::tmu::publish_tmi,
        crate::handlers::tmu::cancel_tmi,
        crate::handlers::tmu::delete_tmi,
        crate::handlers::tmu::list_programs,
        crate::handlers::tmu::upsert_program,
        crate::handlers::tmu::delete_program,
        crate::handlers::tmu::list_ground_stops,
        crate::handlers::tmu::create_ground_stop,
        crate::handlers::tmu::publish_ground_stop,
        crate::handlers::tmu::cancel_ground_stop,
        crate::handlers::tmu::delete_ground_stop,
        crate::handlers::events::list_events,
        crate::handlers::events::get_event,
        crate::handlers::events::get_event_dcc,
        crate::handlers::events::update_event_dcc,
        crate::handlers::feed::feed_status,
        crate::handlers::feed::airport_flow,
        crate::handlers::feed::list_departures,
        crate::handlers::feed::taxi_stats,
        crate::handlers::feed::issue_cfr,
        crate::handlers::feed::release_cfr,
        crate::handlers::audit::list_audit_logs,
        crate::handlers::service_accounts::list_service_accounts,
        crate::handlers::service_accounts::create_service_account,
        crate::handlers::service_accounts::rotate_service_account,
        crate::handlers::service_accounts::disable_service_account,
        crate::handlers::service_accounts::set_service_account_roles,
    ),
    components(schemas(
        crate::models::MeBody,
        crate::models::UserSummary,
        crate::models::FacilityBody,
        crate::models::AccessCatalogBody,
        crate::models::SelfAccessBody,
        crate::models::UserAccessBody,
        crate::models::ScopeAccess,
        crate::models::UpdateUserAccessRequest,
        crate::models::ScopeUpdate,
        crate::models::TmiBody,
        crate::models::CreateTmiRequest,
        crate::models::UpdateTmiRequest,
        crate::models::GateRule,
        crate::models::ProgramBody,
        crate::models::UpsertProgramRequest,
        crate::models::GroundStopBody,
        crate::models::CreateGroundStopRequest,
        crate::models::EventBody,
        crate::models::DccRequestBody,
        crate::models::UpdateDccRequest,
        crate::handlers::feed::FeedStatusBody,
        crate::feed::flow::Flow,
        crate::feed::flow::FlowFlight,
        crate::feed::taxi::TaxiField,
        crate::feed::taxi::TaxiActive,
        crate::models::DepartureFlight,
        crate::models::DeparturesResponse,
        crate::models::IssueCfrRequest,
        crate::models::IssuedCfrBody,
        crate::models::AuditLogEntry,
        crate::models::AuditLogPage,
        crate::models::CreateServiceAccountRequest,
        crate::models::SetServiceAccountRolesRequest,
        crate::models::ServiceAccountBody,
        crate::models::ServiceAccountTokenBody,
    )),
    tags(
        (name = "system", description = "Health"),
        (name = "auth", description = "Authentication + current user"),
        (name = "users", description = "User directory"),
        (name = "facilities", description = "ARTCC directory"),
        (name = "access", description = "Fine-grained access control"),
        (name = "tmu", description = "Traffic management (NTML / ADV / TMI)"),
        (name = "events", description = "VATUSA events + per-event planning"),
        (name = "feed", description = "Live VATSIM traffic feed"),
        (name = "audit", description = "Audit log"),
        (name = "service-accounts", description = "Machine client credentials")
    )
)]
pub struct ApiDoc;
